CREATE DATABASE JOINS
CREATE TABLE EMPLOYEE
(
	EMPLOYEE_ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	FIRST_NAME VARCHAR(20),
	LAST_NAME VARCHAR(20),
	SALARY INT,
	DEPARTMENT VARCHAR(20),
	MANAGER_ID INT
)
ALTER TABLE EMPLOYEE ALTER COLUMN JOINNING_DATE VARCHAR(30),
INSERT INTO EMPLOYEE(FIRST_NAME,LAST_NAME,SALARY,JOINNING_DATE,DEPARTMENT,MANAGER_ID)
VALUES('john','ABRAHAM',1000000,'01-jan-13 12.00.00 AM','BANKING',NULL),
('MICHAEL','CLARKE',800000,'01-jan-13 12.00.00 AM','INSURANCE',1),
('ROY','THOMAS',700000,'01-feb-13 12.00.00 AM','banking',1),
('TOM','JOSE',600000,'01-feb-13 12.00.00 AM','INSURANCE',2),
('JERRY','PINTO',650000,'01-feb-13 12.00.00 AM','INSURANCE',3),
('PHILIP','MATHEW',750000,'01-jan-13 12.00.00 AM','SERVICES',3),
('TESTNAME1','123',650000,'01-jan-13 12.00.00 AM','SERVICES',2),
('TESTNAME2','LNAME%',600000,'01-feb-13 12.00.00 AM','INSURANCE',2)
SELECT * FROM EMPLOYEE

CREATE TABLE Incentives
(
	EMPLOYEE_ID INT CONSTRAINT fk FOREIGN KEY REFERENCES EMPLOYEE(EMPLOYEE_ID) IDENTITY(1,1),
	INCENTIVE_DATE VARCHAR(30),
	INCENTIVE_AMOUNT INT
)
ALTER TABLE INCENTIVES ALTER COLUMN EMPLOYEE_ID INT 
INSERT INTO Incentives(INCENTIVE_DATE,INCENTIVE_AMOUNT)VALUES('01-FEB-13',5000),
('01-FEB-13',3000),
('01-FEB-13',4000);
SELECT * FROM Incentives

1)
SELECT CONCAT(EMP.First_Name,SPACE(2),EMP.Last_Name) AS 'Fullname',	
		EMP.JOINNING_DATE AS 'Joining Date',
		Inc.Incentive_Date AS 'Incentive Date',
		DATEDIFF(YYYY,EMP.JOINNING_DATE,Inc.Incentive_Date) AS 'Differenve'
FROM Employee AS EMP
JOIN Incentives AS Inc
ON EMP.Employee_ID = Inc.EMPLOYEE_ID

2)
SELECT CONCAT(EMP.First_Name,SPACE(2),EMP.Last_Name) AS 'Fullname',	EMP.HireDate AS 'Joining Date',	Inc.Incentive_Date AS 'Incentive Date',	Inc.Incentive_Amount
FROM Employee AS EMP
JOIN Incentives AS Inc
ON EMP.Employee_ID = Inc.EMPLOYEE_ID
WHERE Inc.Incentive_Amount > 3000


3)
SELECT CONCAT(EMP.First_Name,SPACE(2),EMP.Last_Name) AS 'Fullname',	EMP.JOINNING_DATE AS 'Joining Date',Inc.Incentive_Date AS 'Incentive Date',Inc.Incentive_Amount
FROM Employee AS EMP
LEFT JOIN Incentives AS Inc
ON EMP.Employee_ID = Inc.EMPLOYEE_ID

4)
SELECT CONCAT(E2.First_Name,SPACE(1),E2.Last_Name) AS 'Employee Name',E2.Employee_ID AS 'Employee ID',CONCAT(E1.First_Name,SPACE(1),E1.Last_Name) AS 'Manager Name',E1.Employee_ID AS 'Manager ID'
FROM Employee AS E1
RIGHT JOIN  Employee AS E2
ON E2.Manager_ID = E1.EMPLOYEE_ID
ORDER BY E2.EMPLOYEE_ID

5)
SELECT CONCAT(EMP.First_Name,SPACE(2),EMP.Last_Name) AS 'Fullname',	EMP.JOINNING_DATE AS 'Joining Date',Inc.Incentive_Date AS 'Incentive Date',	ISNULL(Inc.Incentive_Amount,0) AS 'Incetive Amont'
FROM Employee AS EMP
LEFT JOIN Incentives AS Inc
ON EMP.Employee_ID = Inc.EMPLOYEE_ID




