SELECT TOP 5 FIRSTNAME AS 'NAME',LASTNAME AS'SURNAME',SALARY FROM EMPLOYEES FOR JSON PATH

DECLARE @json NVARCHAR(MAX)
SET @json=N'{"Employees":[{"NAME":"Steven11","SURNAME":"Steven11","SALARY":5000.00},{"NAME":"Steven1111","SURNAME":"Steven11111","SALARY":50000.00},{"NAME":"Steven","SURNAME":"Steven","SALARY":50000.00},{"NAME":"Alexander","SURNAME":"Hunold","SALARY":9000.00},{"NAME":"Bruce","SURNAME":"Ernst","SALARY":6000.00}]}'

--SELECT JSON_VALUE(@json,'$.Employees[0].NAME')
--SELECT JSON_QUERY(@json,'$.Employees[1]')
--SELECT JSON_MODIFY(@json, '$.Employees[0].NAME', 'Harsh')

IF (ISJSON(@json)>0)
BEGIN

--INSERT INTO EMP 
SELECT * FROM OPENJSON(@json) 
WITH
(
NAME NVARCHAR(50) 'strict $.Employees[0].NAME', 
SURNAME NVARCHAR(50) 'strict $.Employees[0].SURNAME',
SALARY DECIMAL(8,2) 'strict $.Employees[0].SALARY'

)END
CREATE TABLE EMP
(
	NAME NVARCHAR(20),
	SURNAME NVARCHAR(20),
	SALARY DECIMAL(8,2)
)

SELECT * FROM EMP FOR JSON PATH,WITHOUT_ARRAY_WRAPPER
